### PR TITLE
Add 'load' to themepack and languagepack

### PR DESCRIPTION
**Pull request by ssweber**
Doesn't work without it. Do you want to rename themepack (`themepack = ThemePack()` in the code) to theme?

now you call at top of file like:
```
ss.lang.load(ss.lp['monty_python'])
ss.themepack.load(ss.tp_large)
```

Before 3.0 we can finalize what fun language packs you want.
I had to start splitting the dict into 2, or it wouldn't finish.
To get it to be even more crazy, you just put 'super' in front of fun.
So second half of the monty python I did:
`Can you look at this dict and make a super fun monty python version?`

### CODE REVIEW

**Comment by ssweber** [comment]
And maybe we put the themepacks into their own file too:

ss.lang.load(ss.lp['monty_python'])
ss.themepack.load(ss.lp['tp_large'])

**Comment by ssweber** [comment]
or user-defined dicts:

ss.lang.load(mylanguage)
ss.theme.load(mytheme)

**Comment by ssweber** [comment]
Actually, I like themepack better. Ditch that thought. 

Maybe we rename lang to languagepack, since we are calling .load on it.

**Comment by ssweber** [comment]
Or alias it

**Comment by PySimpleSQL** [comment]
Do you think we need a separate loader? The __init__() function itself is a loader and can already use user-defined dicts - if the user defined dict doesn't contain some needed keys, then those ones fail over to the default one

ss.lang = ss.LanguagePack(ss.lp_monty_python)
ss.themepack = ss.ThemePack(ss.tp_large)

**Comment by ssweber** [comment]
Closing this, see my other pull.

**Pull request closed without merging**
