### PR TITLE
Wip

### PR DESCRIPTION
**Pull request by ssweber**
@PySimpleSQL 
Hope this is a little easier to look through!

### CODE REVIEW

**Comment by ssweber** [comment]
There's a bug when you close the quick-editor, all the foreign-key descriptions disappear. trying to figure it out.

**Comment by ssweber** [comment]
Took a second to figure out what was happening! 

When quick_editor was opened, its Form init called auto_add_relationships, duplicating Relationship instances… exposing my bug in table_values that allowed the same column to be processed twice.

**Comment by PySimpleSQL** [comment]
Thanks!  This will help a lot!  I'll review now and hopefully get it merged
in finally!  Again, sorry for the delay.  Getting stuck with all that work
put me behind on literally everything, so the few days I had off were spent
catching up  yard work, projects around the house and family time.
Unfortunately all of that too was from the moment I woke up until bed
time.  I really appreciate all of your patience!

**Review by PySimpleSQL — COMMENTED** [review]
commit looks good!

**Review by PySimpleSQL — COMMENTED** [review]
I really like the LazyTable class - very cool

**Review by PySimpleSQL — COMMENTED** [review]
Perfect!

**Review by PySimpleSQL — APPROVED** [review]

**Comment by ssweber** [comment]
Thanks for merging! And the encouraging words. I know that was a lot to review.

No worries about any delay; gave me plenty of time to test some more, catch some more bugs, and simplify things.

**Pull request merged**
