### PR TITLE
Generated column capturing for Mysql/Postgres/Sqlserver/MsAccess

### PR DESCRIPTION
**Pull request by ssweber**
Also fixed SqlLite so that only generated columns are set as generated

1 - hidden
2 - virtual generated
3 - stored generated

should we skip hidden columns?

### CODE REVIEW

**Review by ssweber — COMMENTED** [review]
FYI - chatgpt wrote the _get_calculated_columns function, with some help prompting from me, so it may be helpful using direct jackcess calls, when needed.

**Comment by ssweber** [comment]
I didn't check if the generated column actually returns correct data... I guess that would come if/when we port orders (or another example with calculated columns) to the other databases. But at least we won't try to write to it :)

**Comment by ssweber** [comment]
seems like sqlalchemy got around the parent/child talk with in Relationships with:
child_table -> **table**
fk_column -> **constrained_column**
parent_table -> **referred_table**
pk_column -> **referred_column**

**Comment by PySimpleSQL** [comment]
Hey, I'll get back to you as soon as I can.  I'm in Canada on a Backcountry
camping/canoeing trip and haven't had signal.   Ill be back on the 23rd

**Comment by ssweber** [comment]
That sounds like a blast!

I’ve been working towards making sure that everything is working ok across sqldrivers.

hopefully by the time you get back I’ll have a readme for you to review, that gives me a nice deadline to work against 😉

**Pull request closed without merging**
