### PR TITLE
Put Msaccess example under a `if main`

### PR DESCRIPTION
**Pull request by ssweber**
Multiprocessing makes duplicate guis on Windows.

See: https://stackoverflow.com/questions/70280881/calling-tkinter-before-multiprocessing-causes-multiple-windows

### CODE REVIEW

**Comment by PySimpleSQL** [comment]
I will check this out as soon as I can.  I am out of time at the moment.  Hopefully I can take a peek later tonight

**Comment by ssweber** [comment]
It has something to do with Windows now supporting “fork”.

so for example, before I made this change, the install Java prompt comes up twice, and the progressanimated never pops up.

**Comment by ssweber** [comment]
*not supporting fork

**Comment by ssweber** [comment]
tomorrow I might have time to create the AnimatedThread version, that uses the hidden window instead of multiprocessing.

**Comment by PySimpleSQL** [comment]
I haven't forgot about this - just got busy for a few days.  I want to try a few more things out to make this more generalized.  I had a threaded verion almost working perfectly, I may play with that some more.  It's a bummer that the multiprocessing acts so differently across OSs!

**Comment by ssweber** [comment]
Yeah it is a bummer. I’ll close this and wait for your threaded version to land.

**Pull request closed without merging**
