### PR TITLE
Simple fix for new 'get_min_pk'

### PR DESCRIPTION
**Pull request by ssweber**
Return 0 if there are no records

### CODE REVIEW

**Comment by ssweber** [comment]
Actually, not quite sure which one is right. Closing so I can test further before your new transform code

**Comment by ssweber** [comment]
Should be

`if records['lowest'] is None: return '0' ## when there are no records.`

It was confusing me, I had a parent/child/grandchild table — and when I created a new parent (with no children), then then all the grandchildren would show up. Well duh - it’s because they didn’t have any parents filtering them. But that only dawned on me now.

**Comment by PySimpleSQL** [comment]
Yeah, this could be a good change.  Should it return 0, or should it return
None and leave it to the end user to determine how to handle this situation?

**Comment by ssweber** [comment]
You’re right. It should return none. Then later where you use it, we need to do an ‘if’, so we don’t pass None to the SQLite query… because that was the error I was fixing.

**Comment by PySimpleSQL** [comment]
Yeah, i was kind of leaning that way too.  Thanks for chiming in, I'll make
that change in just a minute for both the min and the max

**Pull request closed without merging**
