### PR TITLE
Added 16x16 crystal-remix to themepack

### PR DESCRIPTION
**Pull request by ssweber**
image

Working on a few scripts to automatically resize and generate these from freedesktop-compatible iconsets. When I'm done with them, where would you want me to upload them to?

Also learned a few new tricks. If you have custom themepack, and want to use one of the included themepacks, just:

```
custom = custom | ss.tp_crystal_remix
ss.themepack(custom)
```

### CODE REVIEW

**Comment by ssweber** [comment]
Also, should if I do a few of these, do you want to include small and large for both?

tp.name_16
tp.name_22 

?

**Comment by ssweber** [comment]
heres what the 22x22 version looks like:
image

**Comment by ssweber** [comment]
Alternately, I don’t mind not adding these, and just provide a tutorial about how to generate them easily.

**Comment by PySimpleSQL** [comment]
Those look great!  Excellent idea to import them over

**Comment by PySimpleSQL** [comment]
Maybe make anutils folder for tools like this?  I'm sure they would be quite useful to many

**Review by PySimpleSQL — APPROVED** [review]

**Pull request merged**
