### PR TITLE
Clean up delete / duplicate, add duplicate parent or children msg

### PR DESCRIPTION
**Pull request by ssweber**

### CODE REVIEW

**Comment by ssweber** [comment]
- Delete will no longer clear unsaved data in unrelated fields.
- We have forced index to be in bounds in the class function
- Added duplicate choice, this record only, or both record and children.
- end of duplicate had a lot of spurious function calls. Cleaned that up.

**Comment by ssweber** [comment]
Thanks for merging!

**Comment by PySimpleSQL** [comment]
Thanks for the efforts.  The codebase is looking great right now. I'm
hoping to take a breather now and get documentation and examples caught up
and get an update to pypi.

Are you still interested in doing the language pack?  That would be a great
addition at this point!

I'm tied up for the next day or so, but I'll be taking little bites out of
things as I get small windows throughout the day

**Comment by ssweber** [comment]
Totally agree with you. Yes, I plan on doing the language pack next! I like the customization, partly because it’ll take some of the pressure off of us picking the exact right wording for messages 😆 

 The code base is looking good, and functionality behaves like you’d expect. It’s been alot of fun and educational to see how you’ve developed the class structures, and the re-naming efforts.

**Pull request merged**
