### PR TITLE
Rename relationship to be more clear

### PR DESCRIPTION
**Pull request by ssweber**
I think this makes things more clear. Do you agree?

- Relationship.get_relationships_for_table -> Relationship.get_for_table
- Relationship.get_update_cascade_relationships -> Relationship.get_update_cascade_children
- Relationship.get_delete_cascade_relationships -> Relationship.get_delete_cascade_children

### CODE REVIEW

**Comment by PySimpleSQL** [comment]
Lets kick some more ideas around on this (I think it can still be a little confusing)  I'm all for renaming, but I find the parent/child naming conventions can be misleading as well ("children" can be taken multiple ways, and not always related to a relationship for example)

What do you think about these?  I think it's more clear where the returned relationships are coming from
Relationship.get_relationships_for_table -> Relationship.from_table
Relationship.get_update_cascade_relationships -> Relationship.from_update_cascade
Relationship.get_delete_cascade_relationships -> Relationship.from_delete_cascade

**Comment by ssweber** [comment]
Do you think it matters that from_table returns the complete dict, while from_update_cascade returns just a unique list of children/dependents?

Additionally there is:
get_update_cascade_fk_column
get_delete_cascade_fk_column
get_parent, which parent in an update_cascade

… maybe should think about making them more general purposed

**Comment by ssweber** [comment]
What if we combined a few:

rel = Relationship.for_update_cascade(table) would return

rel.parent
rel.fk_column
rel.dependents (unique list of children tables)

likewise for_delete_cascade

**Comment by ssweber** [comment]
Could we do something like:

Relationship.for_update_cascade(table).parent

Relationship.for_update_cascade(table).parent.virtual


Relationship.for_update_cascade(table).dependents

? That would be sorta cool. Maybe thinking too hard here

**Comment by PySimpleSQL** [comment]
I looked at this some more tonight.  Most of these are only called a couple of times total in the code base.

get_relationships_for_table() -> get_relationships() : makes it clear that you're getting multiple relationships (relationship objects)
get_update_cascade_relationships -> get_update_cascade_tables: makes it clear that you're getting multiple tables (list of table names)
get_delete_cascade_relationships -> get_delete_cascade_tables: same as above.  These two would combine well to something like get_cascade_tables(table, cascade="update" )

**Comment by ssweber** [comment]
That sounds good. I’ll close this and redo

**Pull request closed without merging**
