### PR TITLE
Last harmony example

### PR DESCRIPTION
**Pull request by ssweber**
One final idea. I got this after you used Table.Column for the key in record().

Why not just use same concept for selector/action?

And (borrowing from keygen), allow Unique identifier for all 3 by adding a ':' after the table, or table.column name?

### CODE REVIEW

**Comment by PySimpleSQL** [comment]
I finally got around to looking at this.  It is very interesting and it does clean up and harmonize things a lot.

Currently the KeyGen uses ":" as a separator, I would probably want to change that to avoid any kind of confusion in generated key names.

'.' = Table/column separator
':' = custom key separator
'?' = built-in where clause
'_' = new keygen separator?

So in theory, one could have a key for record() that looks like 'Settings.value:debug_on?key=debug, and successive calls would generate actual keys of debug_on, debug_on_1, debug_on_2....

I like it.  I'm going to dig a little be just to be sure it doesn't upset anything major, but this is overall a great idea

**Comment by ssweber** [comment]
#116 probably want to fix this before debugging the built-in where clause.

**Comment by ssweber** [comment]
I tried the underscore, but was bumping into issue with Settings.

Journal_internal works well though.

**Comment by ssweber** [comment]
I agree, 
```
'.' = Table/column separator
':' = custom key separator
'?' = built-in where clause
'_' = new keygen separator
```

would be a great format!

**Comment by ssweber** [comment]
Also might want to call the keygen in actions() before all the .table_inserts… 
So it would be table:mycustomkey_1.table_insert

instead of 
table:mycustomkey.table_insert_1

**Comment by ssweber** [comment]
Closing. Your work in element map allows for a better concept.

**Pull request closed without merging**
