### PR TITLE
Rename TableHeaders to TableColumns

### PR DESCRIPTION
**Pull request by ssweber**
This builds on my Harmony branch.

Totally decline if you want! Just had to put it out there and see if like it this way too.

### CODE REVIEW

**Comment by PySimpleSQL** [comment]
Yeah, i've been wanting to discuss this as well. 
- PySimpleGUI uses headings as a parameter to Table, which TableHeadings gets naming inspiration from
- As you've pointed out, we are building more than just a simple Table heading.
- the .add() method definitely needs renamed.  Perhaps add_column() would be more clear?

So which way produces the least amount of confusions?  Naming to match the parameter it supplies, or naming to match the actual scope of what it does?  I'm on the fence on either of them really!  

I guess I'm not sure that TableColumns is any better or worse when it comes to conveying to the user what it actually does.  Maybe a more general name could help indicate what it is used for?  Examples:
TableHelper, TableWizard, SortableHeader, AdvancedHeader, etc. all convey that it has something to do with helping/improving the Table element.

Before seeing this pull request, I was already thinking if it made more sense to make a special override of sg.Table, called ss.Table (or ss.TableAdvaced, ss.TableExtra, ss.SortedTable, etc) that has all of this extra functionality built in that could be a drop-in replacement for sg.Table - I just haven't had any time to mess around with the concept.

So yeah, in the end I'm with you that something needs to change, I'm just not sure what the best way forward is yet.  Please continue to kick around ideas, I'm sure when one comes around that fits just right it'll be apparent to both of us

**Comment by ssweber** [comment]
I'm a big +1 for passing the object in place of the sg.Table.

See my quick and dirty above. I just called it a TableWidget for now. Your choice on words!
```
sortedtable=ss.TableWidget(sort_enable=True)
sortedtable.add_column('title', 'Title', width=40) # query's column name, then text for header, then space widths
[ss.selector('Journal',sortedtable,key='sel_journal',num_rows=10)],`

**Comment by ssweber** [comment]
You’re probably right that making it a complete replacement, eg a ss.Table probably is the cleanest, but this TableWidget, TableHelper, TableBuilder, insert_name looks almost like the real thing. 

For the code, having it be Table+Something I think helps it differentiate from where we are talking about an actual table in the database

**Comment by ssweber** [comment]
Let me know about the name. How about we call it ss.Table, but internally reference it as a TableWidget for clarity?

 I just need to add the module name to the code to differentiate between it and sg.Table (eg if element == sg.Table or element module + class name == pysimplesql.Table)

**Comment by PySimpleSQL** [comment]
I'm hoping to look at this more later tonight.  I'm still chewing on which
direction to go with this yet

**Comment by ssweber** [comment]
Honestly I can talk myself in a full circle back to your TableHeader w/ renamed add to add_column. Maybe even:

`ss.selector('Journal',sg.Table, headers=headers,
visible_column_map =headers.visible_map, key='sel_journal',num_rows=10)],`

and thus being more explicit about what the class is doing.

**Comment by ssweber** [comment]
The point being… pick your gut because mine doesn’t have a great solution here. 

I feel pretty good about the key placement for selectors and actions though. Did you like that?

**Comment by PySimpleSQL** [comment]
Yeah, I agree.  No matter what I try to come up with, it seems no better or
worse for one reason or another - so at least for now i changed the add
method to add_column

I see what you're saying about the parameter order/placement.  I think I'll
work on that standardization tomorrow.  I made huge strides with docstrings
tonight and experimented with a new ThemePack mechanism, so I should have a
fair amount of time tomorrow to get into this

**Comment by ssweber** [comment]
I saw all your progress! Amazing :)

**Pull request closed without merging**
