### PR TITLE
Langpack v2

### PR DESCRIPTION
**Pull request by ssweber**
Adds our own popups, so we can customize the button text, read changes based on key (instead of button text), and customize the quick_message

### CODE REVIEW

**Comment by ssweber** [comment]
also was sorta on the fence with
```
    'info_popup_auto_close_seconds' : 2,
    'info_popup_alpha_channel' : .85
```
going into ThemePack vs LanguagePack. It's more functionality/looks, so I put into themepack for now.

**Comment by PySimpleSQL** [comment]
ok, I'll hold on merging until I hear back from you.

I agree on your decision to add the popup alpha and auto close to the themepack

**Comment by ssweber** [comment]
The only thing I wish I could figure out, would be to make the popup info non-blocking (eg modal=False, no while-loop. It auto-closes, so I'm going to stop obsessing about it.

I tried throwing it into a 1 second thread, but pysimplegui didn't like that.

**Comment by ssweber** [comment]
just doing a little cleanup and then i'll say merge.

**Comment by ssweber** [comment]
OK! Good to merge

**Comment by ssweber** [comment]
https://user-images.githubusercontent.com/57631333/224160402-fea92e48-ec85-4b32-95a8-5efd66e77f7a.mp4

**Pull request merged**
