### PR TITLE
Small cleanup of logo

### PR DESCRIPTION
**Pull request by PySimpleSQL**
Using ssweber's logo.  Very minor changes:
- converted the pysimplesql text into a path
- got rid of the dropshadow
- changed the canvas size to fit the logo better
- exported a .png for easier preview (especially on mobile)
- added one example where the color scheme was applied to the text

In all I like the version with the black text.  Should we make this official?

### CODE REVIEW

**Review by ssweber — APPROVED** [review]
Yeah looks good!

 I’m going to size one for a favicon/ sg.Window icon this morning (I think it’ll just take reduce the blurs/highlights to crisp it up at low sizes)

**Comment by ssweber** [comment]
If you’re happy with it, I’m good with it being official :)

**Comment by PySimpleSQL** [comment]
Yes, I think it's perfect.  I knew when the right one came across it would
just stick out to me, and this one did.

Do you want to finish your cleanup, and in the end have a logo.svg, a
logo.png in a few sizes as well as icons of just the platters?  The rest of
the concepts can be deleted- they will remain in Git history, but we won't
need them moving forward.  Then we can use the new logo in the readme.md
file :)

**Comment by ssweber** [comment]
yes, sounds like a plan

**Pull request merged**
