### PR TITLE
another preventative key IN callbacks fix

### PR DESCRIPTION
**Pull request by ssweber**

### CODE REVIEW

**Review by PySimpleSQL — COMMENTED** [review]
I'm not sure I know the difference?  Can you explain what is trying to be prevented?

**Comment by ssweber** [comment]
this is where one key is 'key' and the next is 'key2'.

Wouldn't it be that if you setup a callback for 'key2', then test against 'key', it would call callbacks on key?

**Comment by PySimpleSQL** [comment]
Aaah ok I see,

actually in this case, it wouldn't because its searching for a specifc key in a list of keys - where the other issue was looking for a substring in a string

`
d = {
    'key1': 1,
    'key2': 2,
    'key3': 2,
    'key10': 10
}

print('k' in d) # prints False
print('key' in d) # prints False
print('key1' in d) # prints true
print ('key10' in d) # prints true
print ('key20' in d) # prints false
`

**Comment by ssweber** [comment]
ah ok. Does that apply to line 2335 too? (which you merged)

**Comment by PySimpleSQL** [comment]
yep - i missed that one!  It's all good, i reverted just that portion and pushed it in

**Pull request closed without merging**
